name: Android

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Prepare keystore
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
        run: echo -n "$KEYSTORE" | base64 -d > "android/release.jks"

      - name: Copy Android natives
        run: ./gradlew copyAndroidNatives

      - name: Build
        env:
          STORE_PASSWORD: ${{secrets.STORE_PASSWORD}}
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
        run: ./gradlew android:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tixel-android
          path: ./android/build/outputs/apk/release/*.apk