name: Linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Install dependencies
        run: sudo apt -y install freeglut3-dev libopenal-dev

      - name: Build
        run: ./gradlew linkReleaseExecutableLinuxX64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tixel-linux
          path: ./build/bin/linuxX64/releaseExecutable/