name: macOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Build
        run: ./gradlew packageMacosX64AppRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tixel-macos
          path: ./build/tixel-release.app