name: Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Build
        run: ./gradlew linkReleaseExecutableMingwX64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tixel-mingw
          path: ./build/bin/mingwX64/releaseExecutable/